/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by hand (protoc-gen-gogo not available).
// source: api.proto

package v1

import (
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// ContainerLifecycleEvent represents a container lifecycle event type
type ContainerLifecycleEvent int32

const (
	ContainerLifecycleEvent_UNKNOWN    ContainerLifecycleEvent = 0
	ContainerLifecycleEvent_PRE_START  ContainerLifecycleEvent = 1
	ContainerLifecycleEvent_POST_START ContainerLifecycleEvent = 2
	ContainerLifecycleEvent_PRE_STOP   ContainerLifecycleEvent = 3
	ContainerLifecycleEvent_POST_STOP  ContainerLifecycleEvent = 4
)

var ContainerLifecycleEvent_name = map[int32]string{
	0: "UNKNOWN",
	1: "PRE_START",
	2: "POST_START",
	3: "PRE_STOP",
	4: "POST_STOP",
}

var ContainerLifecycleEvent_value = map[string]int32{
	"UNKNOWN":    0,
	"PRE_START":  1,
	"POST_START": 2,
	"PRE_STOP":   3,
	"POST_STOP":  4,
}

func (x ContainerLifecycleEvent) String() string {
	if name, ok := ContainerLifecycleEvent_name[int32(x)]; ok {
		return name
	}
	return "UNKNOWN"
}

// PodAdmissionRequest contains the information sent for pod admission
type PodAdmissionRequest struct {
	// Pod is the pod being admitted, serialized as JSON
	PodJson []byte `protobuf:"bytes,1,opt,name=pod_json,json=podJson,proto3" json:"pod_json,omitempty"`
	// OtherPods are other pods currently on this node, serialized as JSON array
	OtherPodsJson []byte `protobuf:"bytes,2,opt,name=other_pods_json,json=otherPodsJson,proto3" json:"other_pods_json,omitempty"`
}

func (m *PodAdmissionRequest) Reset()         { *m = PodAdmissionRequest{} }
func (m *PodAdmissionRequest) String() string { return "" }
func (*PodAdmissionRequest) ProtoMessage()    {}

func (m *PodAdmissionRequest) GetPodJson() []byte {
	if m != nil {
		return m.PodJson
	}
	return nil
}

func (m *PodAdmissionRequest) GetOtherPodsJson() []byte {
	if m != nil {
		return m.OtherPodsJson
	}
	return nil
}

// PodAdmissionResponse contains the authorizer's decision
type PodAdmissionResponse struct {
	Allowed         bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason          string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message         string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	OverridePodSpec []byte `protobuf:"bytes,4,opt,name=override_pod_spec,json=overridePodSpec,proto3" json:"override_pod_spec,omitempty"`
}

func (m *PodAdmissionResponse) Reset()         { *m = PodAdmissionResponse{} }
func (m *PodAdmissionResponse) String() string { return "" }
func (*PodAdmissionResponse) ProtoMessage()    {}

func (m *PodAdmissionResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *PodAdmissionResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *PodAdmissionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PodAdmissionResponse) GetOverridePodSpec() []byte {
	if m != nil {
		return m.OverridePodSpec
	}
	return nil
}

// ContainerLifecycleRequest contains container lifecycle event information
type ContainerLifecycleRequest struct {
	PodJson       []byte                  `protobuf:"bytes,1,opt,name=pod_json,json=podJson,proto3" json:"pod_json,omitempty"`
	ContainerJson []byte                  `protobuf:"bytes,2,opt,name=container_json,json=containerJson,proto3" json:"container_json,omitempty"`
	ContainerId   string                  `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Event         ContainerLifecycleEvent `protobuf:"varint,4,opt,name=event,proto3,enum=v1.ContainerLifecycleEvent" json:"event,omitempty"`
}

func (m *ContainerLifecycleRequest) Reset()         { *m = ContainerLifecycleRequest{} }
func (m *ContainerLifecycleRequest) String() string { return "" }
func (*ContainerLifecycleRequest) ProtoMessage()    {}

func (m *ContainerLifecycleRequest) GetPodJson() []byte {
	if m != nil {
		return m.PodJson
	}
	return nil
}

func (m *ContainerLifecycleRequest) GetContainerJson() []byte {
	if m != nil {
		return m.ContainerJson
	}
	return nil
}

func (m *ContainerLifecycleRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerLifecycleRequest) GetEvent() ContainerLifecycleEvent {
	if m != nil {
		return m.Event
	}
	return ContainerLifecycleEvent_UNKNOWN
}

// ContainerLifecycleResponse contains the authorizer's response
type ContainerLifecycleResponse struct {
	Success      bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message      string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Measurements map[string]string `protobuf:"bytes,3,rep,name=measurements,proto3" json:"measurements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ContainerLifecycleResponse) Reset()         { *m = ContainerLifecycleResponse{} }
func (m *ContainerLifecycleResponse) String() string { return "" }
func (*ContainerLifecycleResponse) ProtoMessage()    {}

func (m *ContainerLifecycleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ContainerLifecycleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ContainerLifecycleResponse) GetMeasurements() map[string]string {
	if m != nil {
		return m.Measurements
	}
	return nil
}

// PodMeasurementRequest is sent to request pod measurements
type PodMeasurementRequest struct {
	PodJson     []byte `protobuf:"bytes,1,opt,name=pod_json,json=podJson,proto3" json:"pod_json,omitempty"`
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (m *PodMeasurementRequest) Reset()         { *m = PodMeasurementRequest{} }
func (m *PodMeasurementRequest) String() string { return "" }
func (*PodMeasurementRequest) ProtoMessage()    {}

func (m *PodMeasurementRequest) GetPodJson() []byte {
	if m != nil {
		return m.PodJson
	}
	return nil
}

func (m *PodMeasurementRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

// PodMeasurementResponse contains measurement results
type PodMeasurementResponse struct {
	Success      bool              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Measurements map[string]string `protobuf:"bytes,2,rep,name=measurements,proto3" json:"measurements,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Message      string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *PodMeasurementResponse) Reset()         { *m = PodMeasurementResponse{} }
func (m *PodMeasurementResponse) String() string { return "" }
func (*PodMeasurementResponse) ProtoMessage()    {}

func (m *PodMeasurementResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PodMeasurementResponse) GetMeasurements() map[string]string {
	if m != nil {
		return m.Measurements
	}
	return nil
}

func (m *PodMeasurementResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// APIAuthorizationRequest contains information about an incoming API request
type APIAuthorizationRequest struct {
	Path          string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	PodNamespace  string   `protobuf:"bytes,3,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodName       string   `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ContainerName string   `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Command       []string `protobuf:"bytes,6,rep,name=command,proto3" json:"command,omitempty"`
	User          string   `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Groups        []string `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	SourceIp      string   `protobuf:"bytes,9,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
}

func (m *APIAuthorizationRequest) Reset()         { *m = APIAuthorizationRequest{} }
func (m *APIAuthorizationRequest) String() string { return "" }
func (*APIAuthorizationRequest) ProtoMessage()    {}

func (m *APIAuthorizationRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *APIAuthorizationRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *APIAuthorizationRequest) GetPodNamespace() string {
	if m != nil {
		return m.PodNamespace
	}
	return ""
}

func (m *APIAuthorizationRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *APIAuthorizationRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *APIAuthorizationRequest) GetCommand() []string {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *APIAuthorizationRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *APIAuthorizationRequest) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *APIAuthorizationRequest) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

// APIAuthorizationResponse contains the authorizer's decision for API authorization
type APIAuthorizationResponse struct {
	Allowed bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *APIAuthorizationResponse) Reset()         { *m = APIAuthorizationResponse{} }
func (m *APIAuthorizationResponse) String() string { return "" }
func (*APIAuthorizationResponse) ProtoMessage()    {}

func (m *APIAuthorizationResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *APIAuthorizationResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *APIAuthorizationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthorizerService

type AuthorizerServiceClient interface {
	CheckPodAdmission(ctx context.Context, in *PodAdmissionRequest, opts ...grpc.CallOption) (*PodAdmissionResponse, error)
	OnContainerLifecycle(ctx context.Context, in *ContainerLifecycleRequest, opts ...grpc.CallOption) (*ContainerLifecycleResponse, error)
	GetPodMeasurement(ctx context.Context, in *PodMeasurementRequest, opts ...grpc.CallOption) (*PodMeasurementResponse, error)
	CheckAPIAuthorization(ctx context.Context, in *APIAuthorizationRequest, opts ...grpc.CallOption) (*APIAuthorizationResponse, error)
}

type authorizerServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizerServiceClient(cc *grpc.ClientConn) AuthorizerServiceClient {
	return &authorizerServiceClient{cc}
}

func (c *authorizerServiceClient) CheckPodAdmission(ctx context.Context, in *PodAdmissionRequest, opts ...grpc.CallOption) (*PodAdmissionResponse, error) {
	out := new(PodAdmissionResponse)
	err := grpc.Invoke(ctx, "/v1.AuthorizerService/CheckPodAdmission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) OnContainerLifecycle(ctx context.Context, in *ContainerLifecycleRequest, opts ...grpc.CallOption) (*ContainerLifecycleResponse, error) {
	out := new(ContainerLifecycleResponse)
	err := grpc.Invoke(ctx, "/v1.AuthorizerService/OnContainerLifecycle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) GetPodMeasurement(ctx context.Context, in *PodMeasurementRequest, opts ...grpc.CallOption) (*PodMeasurementResponse, error) {
	out := new(PodMeasurementResponse)
	err := grpc.Invoke(ctx, "/v1.AuthorizerService/GetPodMeasurement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizerServiceClient) CheckAPIAuthorization(ctx context.Context, in *APIAuthorizationRequest, opts ...grpc.CallOption) (*APIAuthorizationResponse, error) {
	out := new(APIAuthorizationResponse)
	err := grpc.Invoke(ctx, "/v1.AuthorizerService/CheckAPIAuthorization", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthorizerService

type AuthorizerServiceServer interface {
	CheckPodAdmission(context.Context, *PodAdmissionRequest) (*PodAdmissionResponse, error)
	OnContainerLifecycle(context.Context, *ContainerLifecycleRequest) (*ContainerLifecycleResponse, error)
	GetPodMeasurement(context.Context, *PodMeasurementRequest) (*PodMeasurementResponse, error)
	CheckAPIAuthorization(context.Context, *APIAuthorizationRequest) (*APIAuthorizationResponse, error)
}

func RegisterAuthorizerServiceServer(s *grpc.Server, srv AuthorizerServiceServer) {
	s.RegisterService(&_AuthorizerService_serviceDesc, srv)
}

func _AuthorizerService_CheckPodAdmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodAdmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).CheckPodAdmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthorizerService/CheckPodAdmission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).CheckPodAdmission(ctx, req.(*PodAdmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_OnContainerLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).OnContainerLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthorizerService/OnContainerLifecycle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).OnContainerLifecycle(ctx, req.(*ContainerLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_GetPodMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).GetPodMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthorizerService/GetPodMeasurement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).GetPodMeasurement(ctx, req.(*PodMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizerService_CheckAPIAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizerServiceServer).CheckAPIAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthorizerService/CheckAPIAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizerServiceServer).CheckAPIAuthorization(ctx, req.(*APIAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorizerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AuthorizerService",
	HandlerType: (*AuthorizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPodAdmission",
			Handler:    _AuthorizerService_CheckPodAdmission_Handler,
		},
		{
			MethodName: "OnContainerLifecycle",
			Handler:    _AuthorizerService_OnContainerLifecycle_Handler,
		},
		{
			MethodName: "GetPodMeasurement",
			Handler:    _AuthorizerService_GetPodMeasurement_Handler,
		},
		{
			MethodName: "CheckAPIAuthorization",
			Handler:    _AuthorizerService_CheckAPIAuthorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
